name = "lubna-worker"
main = "src/index.ts"
compatibility_date = "2026-03-22"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_NAME = "Lubna"
APP_URL = "https://lubna.pages.dev"
FRONTEND_ORIGIN = "https://lubna.pages.dev"
GOOGLE_CLOUD_PROJECT_ID = "SET_ME"
GOOGLE_REDIRECT_URI = "https://lubna-worker.sandeepkumarbtech2012.workers.dev/auth/callback"
GOOGLE_CLIENT_ID = "245236117299-hpbhch5kqk5opnbgeqci2v4fhl59m4fu.apps.googleusercontent.com"

[[kv_namespaces]]
binding = "KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID_FROM_CLOUDFLARE_DASHBOARD"

[[d1_databases]]
binding = "DB"
database_name = "lubna-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID_FROM_CLOUDFLARE_DASHBOARD"
