name = "lubna-worker"
main = "src/index.ts"
compatibility_date = "2026-03-22"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_NAME = "Lubna"
APP_URL = "https://lubna.pages.dev"
FRONTEND_ORIGIN = "https://lubna.pages.dev"
GOOGLE_CLOUD_PROJECT_ID = "SET_ME"
GOOGLE_REDIRECT_URI = "https://lubna-worker.sandeepkumarbtech2012.workers.dev/auth/callback"
GOOGLE_CLIENT_ID = "245236117299-hpbhch5kqk5opnbgeqci2v4fhl59m4fu.apps.googleusercontent.com"

[[kv_namespaces]]
binding = "lubna_kv"
id = "4d2f97eb26284d17b30250f185768b03"

[[d1_databases]]
binding = "DB"
database_name = "lubna-db"
database_id = "72f549d1-266e-489b-8ae2-549c0da70e24"
